# web容器配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8888
  connection-timeout: 5000
  context-path: /
spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/

  redis:
      open: false  # 是否开启redis缓存
      database: 5
      host: 172.93.33.78
      port: 6379
      password: y8KwTteyjV4jtrTnEf955vQAFrZ7wz
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis.xml


